version: '3.8'

networks:
  api-network:
    driver: bridge

services:
  db:
    image: redis
    ports: 
      - 6379:6379
    networks:
      - api-network
  api:
    depends_on:
      - db
    build: .
    ports:
      - 3001:3001
    networks:
      - api-network
    environment:
      REDIS_HOST: db
      CLIENT_SECRET: 453000f7-47a0-4489-bc47-891c742650e2      




